apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  labels:
    app: ping-pong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: quay.io/lancelottian/ping-pong:3
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /var/log/ping-pong
          name: log-volume
      imagePullSecrets:
      - name: quayio-regcred
      volumes:
      - name: log-volume
        emptyDir: {}
